package com.recipeManagement.recipe_Management.Model.Enums;

public enum IngredientsType {
    Chicken_Breast,
    Salmon_Fillet,
    Broccoli,
    Mushrooms,
    Bell_Peppers,
    Onions,
    Garlic,
    Tomatoes,
    Lettuce,
    Avocado,
    Rice,
    Pasta,
    Cheese,
    Bread,
    Eggs,
    Bacon,
    Spinach,
    Olive_Oil,
    Soy_Sauce,
    Salt,
    Pepper,
    Chili_Flakes,
    Cumin,
    Paprika,
    Basil,
    Tomato_Sos
}
